ftnw_homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fidonews_editor
        permanent: true

fidonews_editor:
    path: /echo
    defaults: { _controller: FTNWBundle:Editor:groups }

fidonews_group:
    path: /echo/{group_id}
    defaults: { _controller: FTNWBundle:Editor:group }
    requirements:
        group_id: \d+

fidonews_group_list:
    path: /echo/{group_id}/list/{page}
    defaults: { _controller: FTNWBundle:Editor:echomailList, page: 1 }
    requirements:
        group_id: \d+
        page: \d+

fidonews_group_listall:
    path: /echo/{group_id}/listall/{page}
    defaults: { _controller: FTNWBundle:Editor:echomailList, all: true, page: 1 }
    requirements:
        group_id: \d+
        page: \d+

fidonews_list_ops:
    path: /echo/{group_id}/list/operations
    defaults: { _controller: FTNWBundle:Editor:echomailListOps }
    requirements:
        group_id: \d+
        methods: POST

fidonews_message:
    path: /echo/{group_id}/{message_number}
    defaults: { _controller: FTNWBundle:Editor:message }
    requirements:
        group_id: \d+
        message_number: \d+

fidonews_message_bookmark:
    path: /echo/bookmark
    defaults: { _controller: FTNWBundle:Editor:bookmarkEchomail }
    condition: request.isXMLHttpRequest()
    requirements:
        group_id: \d+
        message_number: \d+
        methods: POST

fidonews_post:
    path: /echo/{id}/post
    defaults: { _controller: FTNWBundle:Editor:post }
    requirements:
        id: \d+

fidonews_reply:
    path: /echo/{id}/reply
    defaults: { _controller: FTNWBundle:Editor:reply }
    requirements:
        id: \d+

fidonews_forward:
    path: /echo/{id}/forward
    defaults: { _controller: FTNWBundle:Editor:reply }
    requirements:
        id: \d+

bookmarks_list:
    path: /bookmarks
    defaults: { _controller: FTNWBundle:Editor:bookmarksList }

bookmarks_operations:
    path: /bookmarks/operations
    defaults: { _controller: FTNWBundle:Editor:bookmarksOps }
    requirements:
        methods: POST

netmail:
    path: /netmail
    defaults: { _controller: FTNWBundle:Editor:netmailcheck }

netmail_list:
    path: /netmail/list/{page}
    defaults: { _controller: FTNWBundle:Editor:netmailList, page: 1 }
    requirements:
        page: \d+

netmail_list_all:
    path: /netmail/listall/{page}
    defaults: { _controller: FTNWBundle:Editor:netmailList, all: true, page: 1 }
    requirements:
        page: \d+

netmail_list_ops:
    path: /netmail/list/operations
    defaults: { _controller: FTNWBundle:Editor:netmailListOps }
    requirements:
        methods: POST

netmail_message:
    path: /netmail/{netmail_id}
    defaults: { _controller: FTNWBundle:Editor:netmail }
    requirements:
        netmail_id: \d+

netmail_post:
    path: /netmail/post/{nm}/{rfca}
    defaults: { _controller: FTNWBundle:Editor:netmailPost, nm: null, rfca: null }
netmail_email:
    path: /netmail/email
    defaults: { _controller: FTNWBundle:Editor:netmailPostEmail }

netmail_reply:
    path: /netmail/{id}/reply
    defaults: { _controller: FTNWBundle:Editor:netmailReply }
    requirements:
        id: \d+

point_signin:
    path: /signin
    defaults: { _controller: FTNWBundle:Point:register }

point_login:
    path: /login
    defaults: { _controller: FTNWBundle:Point:login }

point_logout:
    path: /logout
    defaults: { _controller: FTNWBundle:Point:logout }

point_classic_info:
    path: /classic/{num}
    defaults: { _controller: FTNWBundle:Point:classic }
    requirements:
        num: \d+

point_settings:
    path: /settings
    defaults: { _controller: FTNWBundle:Point:settings }

point_faq:
    path: /faq
    defaults: { _controller: FTNWBundle:Point:faq }

point_web_info:
    path: /webbs/{num}
    defaults: { _controller: FTNWBundle:Point:webbs }
    requirements:
        num: \d+

reader_areas_list:
    path: /reader
    defaults: { _controller: FTNWBundle:Reader:areasList }

reader_message_list:
    path: /reader/{area}/{page}
    defaults: { _controller: FTNWBundle:Reader:messageList, page: 1 }
    requirements:
        page: \d+
        area: \d+

uuview_first:
    path: /uuview/{mid}/{num}
    defaults: { _controller: FTNWBundle:UUView:echoMessage, num: 0 }
    requirements:
        mid: \d+
        num: \d+

rest_uplink_new:
    path: /api/uplink/new
    defaults: { _controller: FTNWBundle:Api:uplinkNew }
    requirements:
        methods: POST


uplink_new:
    path:     /api/uplink/new
    defaults: { _controller: FTNWBundle:Api:uplinkNew }
