ftnw_homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fidonews_editor
        permanent: true

fidonews_editor:
    path: /echo
    defaults: { _controller: FTNWBundle:Editor:groups }

fidonews_group:
    path: /echo/{group_id}
    defaults: { _controller: FTNWBundle:Editor:group }
    requirements:
        group_id: \d+

fidonews_group_list:
    path: /echo/{group_id}/list
    defaults: { _controller: FTNWBundle:Editor:echomailList }
    requirements:
        group_id: \d+

fidonews_list_ops:
    path: /echo/{group_id}/list/operations
    defaults: { _controller: FTNWBundle:Editor:echomailListOps }
    requirements:
        group_id: \d+
        methods: POST

fidonews_message:
    path: /echo/{group_id}/{message_number}
    defaults: { _controller: FTNWBundle:Editor:message }
    requirements:
        group_id: \d+
        message_number: \d+

fidonews_post:
    path: /echo/{id}/post
    defaults: { _controller: FTNWBundle:Editor:post }
    requirements:
        id: \d+

fidonews_reply:
    path: /echo/{id}/reply
    defaults: { _controller: FTNWBundle:Editor:reply }
    requirements:
        id: \d+

netmail:
    path: /netmail
    defaults: { _controller: FTNWBundle:Editor:netmailcheck }

netmail_list:
    path: /netmail/list
    defaults: { _controller: FTNWBundle:Editor:netmailList }

netmail_message:
    path: /netmail/{netmail_id}
    defaults: { _controller: FTNWBundle:Editor:netmail }
    requirements:
        netmail_id: \d+

netmail_post:
    path: /netmail/post/{nm}/{rfca}
    defaults: { _controller: FTNWBundle:Editor:netmailPost, nm: null, rfca: null }
netmail_email:
    path: /netmail/email
    defaults: { _controller: FTNWBundle:Editor:netmailPostEmail }

netmail_reply:
    path: /netmail/{id}/reply
    defaults: { _controller: FTNWBundle:Editor:netmailReply }
    requirements:
        id: \d+

point_signin:
    path: /signin
    defaults: { _controller: FTNWBundle:Point:register }

point_login:
    path: /login
    defaults: { _controller: FTNWBundle:Point:login }

point_logout:
    path: /logout
    defaults: { _controller: FTNWBundle:Point:logout }

point_classic_info:
    path: /classic/{num}
    defaults: { _controller: FTNWBundle:Point:classic }
    requirements:
        num: \d+

point_settings:
    path: /settings
    defaults: { _controller: FTNWBundle:Point:settings }

point_faq:
    path: /faq
    defaults: { _controller: FTNWBundle:Point:faq }

point_web_info:
    path: /webbs/{num}
    defaults: { _controller: FTNWBundle:Point:webbs }
    requirements:
        num: \d+

rest_uplink_new:
    path: /api/uplink/new
    defaults: { _controller: FTNWBundle:Api:uplinkNew }
    requirements:
        methods: POST


uplink_new:
    path:     /api/uplink/new
    defaults: { _controller: FTNWBundle:Api:uplinkNew }
