<?php

namespace IgorGoroun\FTNWBundle\Repository;

/**
 * EchoareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchoareaRepository extends \Doctrine\ORM\EntityRepository
{
}
