<?php

namespace IgorGoroun\FTNWBundle\Repository;

/**
 * LastreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastreadRepository extends \Doctrine\ORM\EntityRepository
{
}
