<?php

namespace IgorGoroun\FTNWBundle\Repository;

/**
 * MessageBatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageBatchRepository extends \Doctrine\ORM\EntityRepository
{
}
