<?php

namespace IgorGoroun\FTNWBundle\Repository;

/**
 * MessageCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageCacheRepository extends \Doctrine\ORM\EntityRepository
{
}
