<?php

namespace IgorGoroun\FTNWBundle\Repository;

/**
 * NetmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetmailRepository extends \Doctrine\ORM\EntityRepository
{
}
