<?php

namespace IgorGoroun\FTNWBundle\Repository;

/**
 * PointMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
