<?php

namespace IgorGoroun\FTNWBundle\Repository;

/**
 * UplinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UplinkRepository extends \Doctrine\ORM\EntityRepository
{
}
